### ISSUE TITLE
feat: Ability to map categories to different paths

### ISSUE THREAD

**Issue by FredrikMWold** [ieedan/jsrepo#219] opened 2024-12-01 14:42 UTC
## Description  
I would like the ability to map categories in a registry to specific paths in a project. For example:  

- **Components** maps to `src/components`.  
- **Hooks** maps to `src/hooks`.  
- **Config** maps to `src`.  

## Use Case  
This feature would make it easier to organize projects by connecting registry categories directly to file paths.  

### Validations

- [X] I have checked other issues to see if my feature was already requested or added

**Comment by ieedan** [comment] 2024-12-01 15:20
**So I have thought about this one and I agree this would be really nice.**

I just haven't really come up with a solution that I really like just yet so I would love some feedback on how you would think this would work best!

## Current Idea
We add a `paths` key to the `jsrepo.json` file that maps a category to a local path. Something like:
```jsonc
{
	// ...
	"paths": {
		"components": "./src/lib/components" 
	}
}
```

I think this is probably the best way to do it when adding components but there are a few issues:
1. Because the user can put blocks in an arbitrary path relative paths to blocks in another category i.e. `../<category>/<block>` won't work. The only way this works is if the registry uses path aliases (which are now supported thanks to #215 ) so how to we prevent the user from using paths and breaking their own code in registries that don't support it. Would builds need to fail if a block in one category references something outside of it's category using a relative path?
3. When should these paths be configured? Completely manually? During `init`?

Let me know what you think I definitely think this is possible if we can get these few details ironed out!

**Comment by FredrikMWold** [comment] 2024-12-01 16:05
1. **Cross-Category References**  
   To clarify: is the issue that if a user references a block in another category using a relative path, and those categories have different local paths, the imports would break when added to the project?

2. **Path Configuration Timing**  
   I imagined adding the mapping manually after initialization, but having the option to configure it during `init` would be a useful addition.

I was imagining the same structure as your example.

**Comment by ieedan** [comment] 2024-12-01 16:17
Yes cross category means when the registry has a block in one category that references a block in another category

**Comment by ieedan** [comment] 2024-12-01 16:18
Another problem that still needs to be solved is when the registry has path aliases that the client project doesn't how would those path aliases be added so they are resolved properly?

**Comment by ieedan** [comment] 2024-12-01 16:21
> Another problem that still needs to be solved is when the registry has path aliases that the client project doesn't how would those path aliases be added so they are resolved properly?

I have an idea for this as well but it would be breaking for the jsrepo-manifest.json or we'd have to support multiple config types at the same time

**Comment by FredrikMWold** [comment] 2024-12-01 16:23
> Another problem that still needs to be solved is when the registry has path aliases that the client project doesn't how would those path aliases be added so they are resolved properly?

This could be a partial solution to the issue. By mapping config files from the registry to the `src` directory, the user would be able to set up the alias in the registry as a block.

**Comment by FredrikMWold** [comment] 2024-12-01 16:29
The cross-category concern seems tricky, and this is the first idea that comes to mind: perhaps cross-category imports should be discouraged, and a warning could be issued during the build process

**Comment by ieedan** [comment] 2024-12-01 16:29
Yeah essentially the jsrepo-manifest would have to contain the keys for the path aliases used by the registry and then the user would need to configure those path aliases so that they map correctly in their project. 

I feel like this opens up a new can of worms as far as complexity though.

**Comment by ieedan** [comment] 2024-12-01 16:30
> The cross-category concern seems tricky, and this is the first idea that comes to mind: perhaps cross-category imports should be discouraged, and a warning could be issued during the build process
> 
> 

I don't think it's realistic to expect people not to import things cross category even in your example I'd expect /components to import from /hooks.

**Comment by ieedan** [comment] 2024-12-01 16:46
> This does sound like it will require some complexity to solve. It seems you'd either need to use aliases in some way or rewrite part of the imports when adding the files. At the very least, you would know how to rewrite the `..` in the relative imporr based on the path in the mapping.
> 
> 

Honestly this would be the easiest thing to do it would be trivial to figure out where things are relatively to each other the problem here is language support. 

To do this we actually need to modify the code. Stuff like ts-morph makes this easy but I don't think it's quite as simple for Svelte and Vue...

**Comment by ieedan** [comment] 2024-12-01 16:58
Also sorry if it's coming off like I'm coming up with a ton of excuses for this not to be added I want this to be a thing I'm just trying to explain the issues I have been trying to figure out in order to make this possible!

**Comment by FredrikMWold** [comment] 2024-12-01 17:09
> Also sorry if it's coming off like I'm coming up with a ton of excuses for this not to be added I want this to be a thing I'm just trying to explain the issues I have been trying to figure out in order to make this possible!

You don’t come across that way at all—your concerns seem entirely valid to me.

I’ve been hoping to find something like this ever since I started using shadcn, and it’s already shaping up to be incredibly cool! I just think this could take things to the next level—especially with the ability to seamlessly bundle tailwind-config / css styles / or other configs

**Comment by ieedan** [comment] 2024-12-01 17:17
Im not so sure that having configs in a registry while possible is a good idea since most of the time you'd want to merge it with any existing config which isn't something I think this project would ever support.

I think sharing CSS would be cool. I am not sure if there is any need to resolve dependencies so that we could properly support it though. Especially with unique syntaxes like the new tailwind v4 "@plugin" it may become a bit cumbersome. Maybe it would be better to settle on a partial support for that one. If that's something you'd like to see supported though open up an issue and I think we can get that one done pretty easy.

**Comment by ieedan** [comment] 2024-12-01 17:23
To kind of summarize my thoughts on the state of this issue...

I agree this should be a thing I think I am going to need to just try and make it work and fail until I come up with something that makes sense. 

I don't really care for the mental overhead added with people having to deal with path aliases I don't really want that to be something you have to fully understand to make use of this project. Ideally as a user just adding blocks you wouldn't have to touch a js/tsconfig. I want adding blocks to be as simple as init and then add. 

Please continue to give feedback new perspectives and ideas should help us come up with something that works for everyone!

**Comment by ieedan** [comment] 2024-12-02 15:32
So looking at shadcn-ui the way they handle doing this is a literally `replaceAll` on the imports because they know exactly where things are going to come from.

The problem is that we don't know replacing the paths isn't really feasible. I think we'll need a clever new idea to make this work...

**Comment by FredrikMWold** [comment] 2024-12-02 15:51
Wouldn’t the mapping help determine where to place import from?

My naive thought process is: when adding a block, you could check for cross-category dependencies and see if there’s a corresponding mapping. If there is, the import could then be replaced with the value from the mapping.

**Comment by ieedan** [comment] 2024-12-02 21:53
Okay I think I have an idea that I like now...

Basically on build the `jsrepo-manifest` would now also include an object on each block called `imports` or something along those lines which would basically just be an map with the exact import name as a key and a template as the value:
```jsonc
[
	// ...
	{
		"name": "utils",
		"blocks": [
			{
				"name": "ipv4-address",
				// ...
				"imports": {
					"$types/result": "{{types/result}}",
					"$utils/math/add": "{{utils/math}}/add",
				}
			},
			// ...
	}
]
```

Then when we pull down the block content we do a `replaceAll` on each key with the path created using the template.

Then you do the same thing as mentioned earlier with `jsrepo.json` adding an `aliases` key or something to map each category to a path.
```
{
	// ...
	"paths": {
		"components": "./src/lib/components" 
	}
}
```

This would require no code changes for registry owners (they just need to rebuild the registry).

**Comment by ieedan** [comment] 2024-12-03 13:11
`paths` key will look like:
```jsonc
"paths": {
    "*": "./src/blocks",
    "components": "./src/lib/components",
	"hooks": "./src/lib/hooks"
}
```

`*` will be required and will be the default path blocks are installed to if the category doesn't match any of the other listed keys.

**Comment by FredrikMWold** [comment] 2024-12-03 13:28
Nice! That looks like a great solution to me. 😄

**Comment by ieedan** [comment] 2024-12-03 15:54
So another update I am most of the way through implementation right now just need to finish up the `test` and `diff` commands. 

But so far everything is pretty much working exactly as it should I think the idea is solid just need to figure out the implementation!

**Comment by ieedan** [comment] 2024-12-03 17:26
This is insanely cool I was able to basically replace the shadcn-svelte CLI with jsrepo and I only had to move utils into a folder to do it [demo](https://github.com/ieedan/shadcn-svelte/tree/jsrepo).

I am gonna go to lunch now and I think it's gonna get merged after that unless you can find anything else!

**Comment by FredrikMWold** [comment] 2024-12-03 20:15
Things seems to work like I would expect 😄

**Comment by ieedan** [comment] 2024-12-03 20:17
Nice I have found a few things myself I hopefully I can have something more stable done soon!

**Closed** 2024-12-03 20:25 UTC
Labels: feature

**Comment by ieedan** [comment] 2024-12-03 20:41
Merged! Worked out a few bugs I think it should work pretty good now!
