### ISSUE TITLE
Can't download a category with multiple files in it

### ISSUE THREAD

**Issue by aonoriaga** [ieedan/jsrepo#196] opened 2024-11-28 15:59 UTC
This is my folder structure

![image](https://github.com/user-attachments/assets/5fd89ea6-f58b-4b87-a7a0-d2d8e34cc0ba)

and when i run `jsrepo add`

![error](https://github.com/user-attachments/assets/1b7a19c4-1814-4549-bcb9-8a2b887b954b)

**Comment by ieedan** [comment] 2024-11-28 16:01
How are you building your manifest?

**Comment by aonoriaga** [comment] 2024-11-28 16:06
![image](https://github.com/user-attachments/assets/76cc3a97-0bdc-4978-8ba2-3d328ea8b9d8)
@ieedan 

and this is the manifest

```json
[
	{
		"name": "browser",
		"blocks": [
			{
				"name": "viewport",
				"directory": "src/browser",
				"category": "browser",
				"tests": false,
				"subdirectory": false,
				"files": [
					"viewport.ts"
				],
				"localDependencies": [],
				"dependencies": [],
				"devDependencies": []
			}
		]
	},
	{
		"name": "crash",
		"blocks": [
			{
				"name": "config",
				"directory": "src/crash/config",
				"category": "crash",
				"tests": false,
				"subdirectory": true,
				"files": [
					"index.ts"
				],
				"localDependencies": [
					"crash/domain",
					"browser/viewport",
					"phaser/types"
				],
				"dependencies": [],
				"devDependencies": []
			},
			{
				"name": "domain",
				"directory": "src/crash/domain",
				"category": "crash",
				"tests": false,
				"subdirectory": true,
				"files": [
					"assets.ts",
					"crash.ts",
					"game.ts",
					"socket.ts"
				],
				"localDependencies": [
					"crash/config",
					"typescript/helpers"
				],
				"dependencies": [
					"phaser@^3.87.0",
					"src"
				],
				"devDependencies": []
			},
			{
				"name": "state",
				"directory": "src/crash/state",
				"category": "crash",
				"tests": false,
				"subdirectory": true,
				"files": [
					"dom.state.ts",
					"game.state.ts",
					"params.state.ts",
					"sound.state.ts"
				],
				"localDependencies": [
					"crash/domain"
				],
				"dependencies": [],
				"devDependencies": []
			}
		]
	},
	{
		"name": "http",
		"blocks": [
			{
				"name": "client",
				"directory": "src/http",
				"category": "http",
				"tests": false,
				"subdirectory": false,
				"files": [
					"client.ts"
				],
				"localDependencies": [],
				"dependencies": [],
				"devDependencies": []
			}
		]
	},
	{
		"name": "phaser",
		"blocks": [
			{
				"name": "Parallax",
				"directory": "src/phaser",
				"category": "phaser",
				"tests": false,
				"subdirectory": false,
				"files": [
					"Parallax.ts"
				],
				"localDependencies": [],
				"dependencies": [
					"phaser@^3.87.0"
				],
				"devDependencies": []
			},
			{
				"name": "types",
				"directory": "src/phaser",
				"category": "phaser",
				"tests": false,
				"subdirectory": false,
				"files": [
					"types.ts"
				],
				"localDependencies": [],
				"dependencies": [
					"@esotericsoftware/spine-phaser@^4.2.66"
				],
				"devDependencies": []
			}
		]
	},
	{
		"name": "typescript",
		"blocks": [
			{
				"name": "helpers",
				"directory": "src/typescript",
				"category": "typescript",
				"tests": false,
				"subdirectory": false,
				"files": [
					"helpers.ts"
				],
				"localDependencies": [],
				"dependencies": [],
				"devDependencies": []
			}
		]
	}
]

```

**Comment by ieedan** [comment] 2024-11-28 16:10
The build actually looks okay it looks like src may be imported incorrectly or its an edge case I haven't accounted for what is the exact error you are getting?

**Comment by aonoriaga** [comment] 2024-11-28 16:14
when trying to do `add` it hangs up

as a colour detail, I think it would be good to detect that if you have multiple files in the root, allow you to choose which ones to download.

**Comment by aonoriaga** [comment] 2024-11-28 16:18
How did you think about it when creating the tool?

That each block is inside a folder?

**Comment by ieedan** [comment] 2024-11-28 16:19
So each block is either an individual file or a folder which is contained in a category

The --dirs flag args are the folders containing the category folders

**Comment by ieedan** [comment] 2024-11-28 16:21
I have a repo that uses both github/ieedan/std and that is currently working fine. It generally serves as a pretty good test bench...

**Comment by ieedan** [comment] 2024-11-28 16:21
Can you try and create a small public reproduction for me?

**Comment by aonoriaga** [comment] 2024-11-28 16:23
ok, but let me check your repository to see if I can find something.

**Comment by aonoriaga** [comment] 2024-11-28 16:28
the difference is that I'm exporting in the same declaration (at least looking at your repository) plus your manifest, I create an object inside the blocks for each file, in my case it creates one only with ‘files’ inside it, where each file in theory is each one of my blocks, you know what I mean?

this is a block in my manifest

```json
```

**Comment by ieedan** [comment] 2024-11-28 16:30
yeah right now we are comparing apples to oranges a bit look at the `math` block as that is using the same modules structure as your project

**Comment by ieedan** [comment] 2024-11-28 16:37
also even if you literally just create a repo with only the import statements present as long as it is public that works for me!

**Comment by arielonoriaga** [comment] 2024-11-28 17:21
Here is an example [repository](https://github.com/arielonoriaga/jsrepo-bug/blob/main/src/print/print.ts)

Try to download that module from your cli

**Comment by ieedan** [comment] 2024-11-28 17:25
Looking now...

**Comment by ieedan** [comment] 2024-11-28 17:29
What operating system are you on?

**Comment by ieedan** [comment] 2024-11-28 17:37
I still cannot reproduce this issue on windows I think I can see it in stackblitz though so I am adding more verbose logging.

**Comment by ieedan** [comment] 2024-11-28 17:37
Are you guys able to even install from std?

**Comment by ieedan** [comment] 2024-11-28 17:50
This is really really weird. I have no problems installing this on either my linux or my windows machine. But then when I run this in stackblitz it hangs?

![image](https://github.com/user-attachments/assets/d42301e9-5353-4510-b018-3d4f214bff43)

**Comment by ieedan** [comment] 2024-11-28 18:12
Gonna keep looking at this down to the wire. But I have a hard cutoff at 12:30 central so this may have to wait we'll see.

**Comment by aonoriaga** [comment] 2024-11-28 18:41
i'm in ubuntu 24

**Comment by ieedan** [comment] 2024-11-28 18:43
So I think I found the issue just merged #205 for some reason the built in fetch in some environments would infinitely hang. So I am now using node fetch.

Please try 1.13.0 and let me know if you still have your issue.

**Comment by aonoriaga** [comment] 2024-11-28 18:46
> So I think I found the issue just merged #205 for some reason the built in fetch in some environments would infinitely hang. So I am now using node fetch.
> 
> Please try `1.13.0` and let me know if you still have your issue.

nothing, still the same

**Comment by ieedan** [comment] 2024-11-28 18:49
hmmm I think I was troubleshooting a totally different issue is that really all it says?

**Comment by ieedan** [comment] 2024-11-28 18:51
oohhhhh wait

No this is what I thought the original issue was. I think I know where to look now.

Unfortunately though I can't spend anymore time on this it's family time I'll get to it as soon as I can sorry!

**Comment by aonoriaga** [comment] 2024-11-28 18:51
np @ieedan

**Comment by aonoriaga** [comment] 2024-11-28 18:51
no rush

**Comment by ieedan** [comment] 2024-11-29 12:32
Tried this on my Linux machine on Ubuntu 24 and I could reproduce it on `1.12.5` or `1.13.1`.

Please run:
```bash
jsrepo -V
```

Maybe I am still missing something with reproduction as well...

**Comment by ieedan** [comment] 2024-12-02 13:26
Yeah I really need a reproduction I can work with I haven't been able to reproduce this anywhere.

If you can try and reproduce in a stackblitz or something that would be preferable. I have a ubuntu machine at home and I haven't been able to reproduce that there either.

**Comment by aonoriaga** [comment] 2024-12-02 13:47
ok, you're right, I can't replicate it in stackblitz.

Is there anything that uses the library that I need to have updated or check for a possible different version on my pc?

**Comment by ieedan** [comment] 2024-12-02 13:51
I don't believe so it should be pretty much self contained you could try uninstalling and reinstalling it completely? Are you using a global install?

**Comment by aonoriaga** [comment] 2024-12-02 13:53
maybe I misspelled

No, I'm using it as a dependency

**Comment by ieedan** [comment] 2024-12-02 15:14
Can you make sure you are logged out and try and access the public repo you sent to me:
```
pnpm dlx jsrepo auth --logout
```

**Comment by ieedan** [comment] 2024-12-02 15:25
Try and replicate on your public repo the SS you sent is still on the private

**Comment by ieedan** [comment] 2024-12-03 21:11
Any luck reproducing this?

**Comment by ieedan** [comment] 2024-12-04 12:35
Doing to close this for not if you can give me a reproduction then I can reopen it!

**Comment by ieedan** [comment] 2024-12-04 15:14
In a twisted turn of events I found myself replicating this issue just now while testing another release. It seems like a really weird combination of events to make this happen I am really not sure why it is this hard to reproduce though.

In any case I am going to reopen this the fix will be present in the next release and fingers cross that works for you!

**Comment by ieedan** [comment] 2024-12-04 15:17
Can you please try the preview with if you have the chance:
```
npx https://pkg.pr.new/ieedan/jsrepo@0169655 add
```

**Comment by ieedan** [comment] 2024-12-04 15:43
Also really sorry about this one it was not an easy reproduction!

**Comment by arielonoriaga** [comment] 2024-12-05 18:07
np bro

i try to add the repository and now i get this error:

![image](https://github.com/user-attachments/assets/fb0ae01c-596f-45c1-9f3a-8622e2126200)

**Comment by ieedan** [comment] 2024-12-05 18:08
Now all you need to do is rebuild your registry with the latest version

**Comment by arielonoriaga** [comment] 2024-12-05 18:08
mb, yes, i now using latest, i will test

**Comment by arielonoriaga** [comment] 2024-12-05 18:13
something strange, is that doing the init, it asked me where I wanted to save the files (I indicated src/blocks) and then when choosing a file to clone, it asked me where it should go (i.e. it asked me again for the directory, I indicated ./src/blocks/{name}) and it didn't create it or clone it.

![image](https://github.com/user-attachments/assets/4ad3734a-7474-48db-93c9-7f583a786bf2)
![image](https://github.com/user-attachments/assets/f0e949b7-f87a-4d7f-b261-f1fba1e4c5d0)

**Comment by ieedan** [comment] 2024-12-05 18:16
Haven't come across that yet are you able to reproduce that one in a stackblitz?

**Comment by ieedan** [comment] 2024-12-05 18:17
Also send your jsrepo.json

**Comment by arielonoriaga** [comment] 2024-12-05 18:17
`{
	"$schema": "https://unpkg.com/jsrepo@1.17.2/schemas/project-config.json",
	"repos": [
		"github/company/repo"
	],
	"includeTests": false,
	"watermark": true,
	"paths": {
		"*": "./src/blocks",
		"colors": "./src/blocks/colors"
	}
}
`

**Comment by ieedan** [comment] 2024-12-05 18:19
> ```json
> 
> {
> 
> 	"$schema": "https://unpkg.com/jsrepo@1.17.2/schemas/project-config.json",
> 
> 	"repos": [
> 
> 		"github/company/repo"
> 
> 	],
> 
> 	"includeTests": false,
> 
> 	"watermark": true,
> 
> 	"paths": {
> 
> 		"*": "./src/blocks",
> 
> 		"colors": "./src/blocks/colors"
> 
> 	}
> 
> }
> 
> ```

Yeah that looks correct

**Comment by arielonoriaga** [comment] 2024-12-05 18:21
back to the original issue, now if I try to clone the files that are broken

I get this

![image](https://github.com/user-attachments/assets/91e6385a-258e-4c2a-826d-914684fce0a7)

**Comment by ieedan** [comment] 2024-12-05 18:23
> it seems that there is some kind of circular reference basically

Yes I think this is the original issue.

You can try and track it down for now and when I have the chance I can create a rule for it to try and catch it early.

**Comment by arielonoriaga** [comment] 2024-12-05 18:26
what I'm seeing is that if file A for example has some type definition that needs another file, we'll call it B, we import it, if it also uses a type from file A, there's the problem, I guess if I separate this in different files it wouldn't happen, but it seems to be like that.

At least that's what I saw in my code

**Comment by ieedan** [comment] 2024-12-05 18:31
Does it work when you change it

**Comment by arielonoriaga** [comment] 2024-12-05 18:34
still happens, as well as it does not show me multiple files inside the folder

I don't know if it's because it is src/folder1/folder2/file{n}

**Comment by arielonoriaga** [comment] 2024-12-05 18:38
i will try

**Comment by arielonoriaga** [comment] 2024-12-05 18:38
I'm a bit busy with work at the moment so I'll do it later.

**Comment by ieedan** [comment] 2024-12-05 18:48
https://github.com/ieedan/jsrepo-cd

Okay I was able to produce it pretty quickly.

**Comment by ieedan** [comment] 2024-12-05 19:16
Okay so download `1.17.3` and run build again.

I just added a `no-circular-dependency` rule that should help you track this down.

Should output something like:
```
 ERROR  There is a circular dependency in utils/math: utils/math -> types/point -> utils/math no-circular-dependency
```

**Comment by ieedan** [comment] 2024-12-05 19:34
I would still recommend you solve the circular dependency but in `1.17.3` I have fixed the CLI so that it won't crash if there is a circular dependency.

**Comment by ieedan** [comment] 2024-12-05 19:35
Try that one out and we should be able to close this out.

**Comment by ieedan** [comment] 2024-12-09 19:22
Is this fixed for you now?

**Comment by ieedan** [comment] 2024-12-10 17:56
> seems to be working already,
> 
> 
> 
> It just doesn't show the multiple files inside the folder and directly clones the whole module, but it works.

This could be the intended behavior a category will have blocks that can be individually installed where as a block will install anything in its directory. You can look at the manifest file to see how it's structured.

**Comment by arielonoriaga** [comment] 2024-12-10 18:00
> > seems to be working already,
> > It just doesn't show the multiple files inside the folder and directly clones the whole module, but it works.
> 
> This could be the intended behavior a category will have blocks that can be individually installed where as a block will install anything in its directory. You can look at the manifest file to see how it's structured.

When i try to a new build i got this msg
```sh
Built /home/$HOME/Projects/company/repo/src
│
▲  Something went wrong
```

**Comment by ieedan** [comment] 2024-12-10 18:02
Whats your build config or command

**Comment by arielonoriaga** [comment] 2024-12-10 18:04
build cmd `"build:registry": "jsrepo build"`

config:

```json
{
	"$schema": "https://unpkg.com/jsrepo@1.19.1/schemas/registry-config.json",
	"dirs": [
		"./src"
	],
	"doNotListBlocks": [],
	"doNotListCategories": [],
	"excludeDeps": [],
	"includeBlocks": [],
	"includeCategories": [],
	"excludeBlocks": [],
	"excludeCategories": []
}
```

**Comment by ieedan** [comment] 2024-12-10 18:05
Can you recreate this in the example repo or a stackblitz?

**Comment by arielonoriaga** [comment] 2024-12-10 18:11
i dont have time for that bro now..

Its okey np, I'll figure it out. thanks.

**Closed** 2024-12-10 18:37 UTC
Labels: bug
